name: Docker build and push
on:
  push:
    paths:
      - 'argocd/image-updater/nginx-docker/**'
    branches: 
      - main
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: docker-push-tagged
        name: Build Docker image and push to DockerHub
        uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
        with:
          platforms: linux/amd64
          push: true
          context: argocd/image-updater/nginx-docker
          tags: |
              alvarof2/nginx:latest
